## NB eg: 1

In [2]:
import numpy as np
import pandas as pd 
from sklearn.naive_bayes import GaussianNB

In [3]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score, train_test_split

In [4]:
data= pd.read_csv("https://raw.githubusercontent.com/dhirajk100/Naive-Bayes/master/Naive-Bayes-Classification-Data.csv")

In [5]:
data.head()

glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [6]:
x = data.drop('diabetes', axis = 1)
y = data['diabetes']
train,test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 6543)

In [7]:
def model_fit(alg,train,test,y_train,y_test,if_cv = True,cv_folds = 5):
    alg.fit(train,y_train)
    
    #performing Cross Validation
    if if_cv: 
        cv_score = cross_val_score(alg,train,y_train,cv = cv_folds,scoring = 'f1_macro')
    
    predictions = alg.predict(test)
    
    #Print 
    print("\n Model Report")
    print(classification_report(y_test,predictions))
    
    if if_cv: 
        print("CV REPORT :- Mean - %.7g | Std - %.7g | Min - %.7g | Max - %.7g"%(np.mean(cv_score),np.std(cv_score),np.min(cv_score),np.max(cv_score)))
    
    print('-'*100)
    print(confusion_matrix(y_test,predictions))

In [8]:
model = GaussianNB()
model_fit(model,train,test,y_train,y_test)


 Model Report
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       130
           1       0.93      0.95      0.94       119

    accuracy                           0.94       249
   macro avg       0.94      0.94      0.94       249
weighted avg       0.94      0.94      0.94       249

CV REPORT :- Mean - 0.9315577 | Std - 0.0274001 | Min - 0.8991654 | Max - 0.9599929
----------------------------------------------------------------------------------------------------
[[121   9]
 [  6 113]]


## NB Eg: 2

In [9]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [10]:
adult_df_rev = pd.read_csv(r'C:\Users\Mohamed.Imran\Desktop\Imran\Inceptez\KNN&NB\adult_nb.csv')
adult_df_rev[:3]

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   

        marital_status          occupation    relationship    race    sex  \
0        Never-married        Adm-clerical   Not-in-family   White   Male   
1   Married-civ-spouse     Exec-managerial         Husband   White   Male   
2             Divorced   Handlers-cleaners   Not-in-family   White   Male   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K

In [11]:
adult_df_rev['income'] = np.where(adult_df_rev['income'] == ' <=50K', 0, 1)

In [12]:
for col in adult_df_rev.columns:
    print(col, ":", sum(adult_df_rev[col].isna()))

age : 0
workclass : 1836
fnlwgt : 0
education : 0
education_num : 0
marital_status : 0
occupation : 1843
relationship : 0
race : 0
sex : 0
capital_gain : 0
capital_loss : 0
hours_per_week : 0
native_country : 583
income : 0


In [13]:
adult_df_rev.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week        income  
count    32561.000000  32561.000000  
mean        40.437456      0.240810  
std         12.347429      0.427581  
min          1.000000      0.000000  
25%         40.000000      0.000000  
50%         40.000000      0.000000  
75%         45.000000      0.000000  
max         99.000000      1.000000

In [14]:
# adult_df_rev.describe(include='all')['workclass'][2]

In [15]:
for value in ['workclass', 'occupation', 'native_country']:
    adult_df_rev[value].replace(np.nan, adult_df_rev.describe(include='all')[value][2], inplace= True)

In [16]:
adult_df_rev.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [17]:
le_list = adult_df_rev.select_dtypes(['object']).columns.tolist()

In [18]:
le = preprocessing.LabelEncoder()

In [19]:
for i in le_list:
    adult_df_rev[i] = le.fit_transform(adult_df_rev[i])

In [20]:
adult_df_rev[:4]

age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          6   77516          9             13               4   
1   50          5   83311          9             13               2   
2   38          3  215646         11              9               0   
3   53          3  234721          1              7               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           0             1     4    1          2174             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   

   hours_per_week  native_country  income  
0              40              38       0  
1              13              38       0  
2              40              38       0  
3              40              38       0

In [21]:
scale_cols = adult_df_rev.columns[:-1].tolist()

In [22]:
scale_cols

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education_num',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital_gain',
 'capital_loss',
 'hours_per_week',
 'native_country']

In [23]:
scaled_features = {}

for col in scale_cols:
    mean, std = adult_df_rev[col].mean(), adult_df_rev[col].std()
    scaled_features[col] = [mean, std]
    adult_df_rev.loc[:, col] = (adult_df_rev[col] - mean)/std

In [24]:
#train test split

features = adult_df_rev.values[:,:14]
target = adult_df_rev.values[:,14]
features_train, features_test, target_train, target_test = train_test_split(features,target, test_size = 0.33, random_state = 10)

In [25]:
adult_df_rev['income'].unique()

array([0, 1], dtype=int64)

In [26]:
#Naive Bayes

clf = GaussianNB()
clf.fit(features_train, target_train)
target_pred = clf.predict(features_test)

In [27]:
accuracy_score(target_test, target_pred)

0.8014144798064397

In [28]:
print(confusion_matrix(target_test, target_pred))

[[7721  435]
 [1699  891]]


In [29]:
print(classification_report(target_test, target_pred))

              precision    recall  f1-score   support

         0.0       0.82      0.95      0.88      8156
         1.0       0.67      0.34      0.46      2590

    accuracy                           0.80     10746
   macro avg       0.75      0.65      0.67     10746
weighted avg       0.78      0.80      0.78     10746

